var obj = [
       ["heb", "hebt", "heeft", "hebben", "hebben", "hebben"], 
       ["ga", "gaat", "gaat", "gaan", "gaan", "gaan"], 
       ["ben", "bent", "is", "zijn", "zijn", "zijn"], 
       ["kom", "komt", "komt", "komen", "komen", "komen"], 
       ["loop", "loopt", "loopt", "lopen", "lopen", "lopen"], 
       ["lees", "leest", "leest", "lezen", "lezen", "lezen"], 
       ["eet", "eet", "eet", "eten", "eten", "eten"], 
       ["zie", "ziet", "ziet", "zien", "zien", "zien"], 
       ["doe", "doet", "doet", "doen", "doen", "doen"], 
       ["drink", "drinkt", "drinkt", "drinken", "drinken", "drinken"], 
       ["werk", "werkt", "werkt", "werken", "werken", "werken"], 
       ["zeg", "zegt", "zegt", "zeggen", "zeggen", "zeggen"], 
       ["zal", "zult", "zal", "zullen", "zullen", "zullen"], 
       ["zou", "zou", "zou", "zouden", "zouden", "zouden"], 
       ["word", "wordt", "wordt", "worden", "worden", "worden"], 
       ["werd", "werd", "werd", "werden", "werden", "werden"], 
       ["mag", "mag", "mag", "mogen", "mogen", "mogen"], 
       ["mocht", "mocht", "mocht", "mochten", "mochten", "mochten"], 
       ["kan", "kunt", "kan", "kunnen", "kunnen", "kunnen"], 
       ["kon", "kon", "kon", "konden", "konden", "konden"], 
      ];
            

var objNotes = [
        {notes: []},
        {notes: ["hebben", "to have"]}, 
        {notes: ["gaan", "to go"]}, 
        {notes: ["zijn", "are"]}, 
        {notes: ["komen", "to come"]}, 
        {notes: ["lopen", "to walk"]}, 
        {notes: ["lezen", "to read"]}, 
        {notes: ["eten", "to eat"]}, 
        {notes: ["zien", "to see"]}, 
        {notes: ["doen", "to do"]}, 
        {notes: ["drinken", "to drink"]}, 
        {notes: ["werken", "to work"]}, 
        {notes: ["zeggen", "to say"]}, 
        {notes: ["zullen", "shall/will"]}, 
        {notes: ["zouden", "would"]}, 
        {notes: ["worden", "am"]}, 
        {notes: ["werden", "was/were"]}, 
        {notes: ["mogen", "may"]}, 
        {notes: ["mochten", "was/were allowed"]}, 
        {notes: ["kunnen", "can"]}, 
        {notes: ["konden", "could"]}, 
               
]

var objNumbers = [
    {number: [1, "één", "one"]},
    {number: [2, "twee", "two"]},
    {number: [3, "drie", "three"]},
    {number: [4, "vier", "four"]},
    {number: [5, "vijf", "five"]},
    {number: [6, "zes", "six"]},
    {number: [7, "zeven", "seven"]},
    {number: [8, "acht", "eight"]},
    {number: [9, "negen", "nine"]},
    {number: [10, "tien", "ten"]},
    {number: [11, "elf", "eleven"]},
    {number: [12, "twalf", "twelve"]},
    {number: [13, "dertien", "thirteen"]},
    {number: [14, "viertien", "fourteen"]},
    {number: [15, "vijftien", "fifteen"]},
    {number: [16, "zestien", "sixteen"]},
    {number: [17, "zeventien", "seventeen"]},
    {number: [18, "achttien", "eighteen"]},
    {number: [19, "negentien", "nineteen"]},
    {number: [20, "twintig", "twenty"]},
    {number: [21, "éénentwintig", "twenty-one"]},
    {number: [22, "tweeëntwintig", "twenty-two"]},
    {number: [23, "drieëntwintig", "twenty-three"]},
    {number: [24, "vierenttwintig", "twenty-four"]},
    {number: [25, "vijfentwintig", "twenty-five"]},
    {number: [26, "zesentwintig", "twenty-six"]},
    {number: [27, "zevenentwintig", "twenty-seven"]},
    {number: [28, "achtentwintig", "twenty-eight"]},
    {number: [29, "negenentwintig", "twenty-nine"]},
    {number: [30, "dertig", "thirty"]},
    {number: [31, "éénendertig", "thirty-one"]},
    {number: [32, "tweeëndertig", "thirty-two"]},
    {number: [33, "drieëndertig", "thirty-three"]},
    {number: [34, "vierendertig", "thirty-four"]},
    {number: [35, "vijfendertig", "thirty-five"]},
    {number: [36, "zesendertig", "thirty-six"]},
    {number: [37, "zevenenderig", "thirty-seven"]},
    {number: [38, "achtendertig", "thirty-either"]},
    {number: [39, "negenendertig", "thirty-nine"]},
    {number: [40, "viertig", "forty"]},
    {number: [41, "eenenviertig", "forty-one"]},
    {number: [42, "tweeënviertig", "forty-two"]},
    {number: [43, "drieënviertig", "forty-three"]},
    {number: [44, "vierenviertig", "forty-four"]},
    {number: [45, "vijfenviertig", "forty-five"]},
    {number: [46, "zesenviertig", "forty-six"]},
    {number: [47, "zevenenviertig", "forty-seven"]},
    {number: [48, "achtenviertig", "forty-eight"]},
    {number: [49, "negenenviertig", "forty-nine"]},
    {number: [50, "vijftig", "fifty"]},
    {number: [51, "éénenvijftig", "fifty-one"]},
    {number: [52, "tweeënvijftig", "fifty-two"]},
    {number: [53, "drieënvijftig", "fifty-three"]},
    {number: [54, "vierenvijftig", "fifty-four"]},
    {number: [55, "vijfenvijftig", "fifty-five"]},
    {number: [56, "zesenvijftig", "fifty-six"]},
    {number: [57, "zevenenvijftig", "fifty-seven"]},
    {number: [58, "achtenvijftig", "fifty-eight"]},
    {number: [59, "negenenvijftig", "fifty-nine"]},
    {number: [60, "zestig", "sixty"]},
    {number: [61, "eenenzestig", "sixty-one"]},
    {number: [62, "tweeënzestig", "sixty-two"]},
    {number: [63, "drieënzestig", "sixty-three"]},
    {number: [64, "vierenzestig", "sixty-four"]},
    {number: [65, "vijfenzestig", "sixty-five"]},
    {number: [66, "zesenzestig", "sixty-six"]},
    {number: [67, "zevenenzestig", "sixty-seven"]},
    {number: [68, "achtenzestig", "sixty-eight"]},
    {number: [69, "negenenzestig", "sixty-nine"]},
    {number: [70, "zeventig", "seventy"]},
    {number: [71, "eenenzeventig", "seventy-one"]},
    {number: [72, "tweeënzeventig", "seventy-two"]},
    {number: [73, "drieënzeventig", "seventy-three"]},
    {number: [74, "vierenzeventig", "seventy-four"]},
    {number: [75, "vijfenzeventig", "seventy-five"]},
    {number: [76, "zesenzeventig", "seventy-six"]},
    {number: [77, "zevenenzeventig", "seventy-seven"]},
    {number: [78, "achtenzeventig", "seventy-eight"]},
    {number: [79, "negenenzeventig", "seventy-nine"]},
    {number: [80, "tachtig", "eighty"]},
    {number: [81, "eenentachtig", "eighty-one"]},
    {number: [82, "tweenëntachtig", "eighty-two"]},
    {number: [83, "drieëntachtig", "eighty-three"]},
    {number: [84, "vierentachtig", "eighty-four"]},
    {number: [85, "vijfentachtig", "eighty-five"]},
    {number: [86, "zesentachtig", "eighty-six"]},
    {number: [87, "zevenentachtig", "eighty-seven"]},
    {number: [88, "achtentachtig", "eighty-eight"]},
    {number: [89, "negenentachtig", "eighty-nine"]},
    {number: [90, "negentig", "ninety"]},
    {number: [91, "eenennegentig", "ninety-one"]},
    {number: [92, "tweeënnegentig", "ninety-two"]},
    {number: [93, "drieënnegentig", "ninety-three"]},
    {number: [94, "vierennegentig", "ninety-four"]},
    {number: [95, "vijfennegentig", "ninety-five"]},
    {number: [96, "zesennegentig", "ninety-six"]},
    {number: [97, "zevenennegentig", "ninety-seven"]},
    {number: [98, "achtennegentig", "ninety-eight"]},
    {number: [99, "negenennegentig", "ninety-nine"]},
    {number: [100, "honderd", "one hundred"]},
    {number: [1000, "duizend", "one thousand"]},
    {number: [10000, "tien duizend", "ten thousand"]},
    {number: [100000, "honderdduizend", "one hundred thousand"]},
    {number: [1000000, "een miljoen", "one million"]},
    {number: [10000000, "tien miljoen", "ten million"]},
    {number: [100000000, "honderd miljoen", "one hundred million"]},

    


    

]

            
var objx = [
            ["heb", "hebt", "heeft", "hebben", "hebben", "hebben"],
            ["ga", "gaat", "gaat", "gaan", "gaan", "gaan"],
            ["ben", "bent", "is", "zijn", "zijn", "zijn"],
            ["zeg", "zegt", "zegt", "zeggen", "zeggen", "zeggen"]
        ]
var objy = [
            {"hebben": 
                ["heb", "hebt", "heeft", "hebben", "hebben", "hebben"]},
            {"gaan": 
                ["ga", "gaat", "gaat", "gaan", "gaan", "gaan"]},
            {"zijn": ["ben", "bent", "is", "zijn", "zijn", "zijn"]}
                  ];
        